import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import styles from "../styles/Home.module.css";
import hero from "../public/img/hero-banner.jpg";
import placeholder from "../public/img/placeholder.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.hero}>
          Hero Banner
          <Image
            src={hero}
            alt="Hero Banner"
            layout="responsive"
            placeholder={placeholder}
            priority
          />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
